excluded:
   - gaiosTests
   - gaiosUITests
   - gdk*
   - tools
   - Pods
   - gaios/GreenApplication.swift
   - gaios/Wallet/Views/SlidingButton.swift
   - gaios/Helpers/AuthenticationTypeHandler.swift

identifier_name:
   severity: warning
   validates_start_with_lowercase: false
   min_length: 1

cyclomatic_complexity:
   ignores_case_statements: true

disabled_rules:
   - force_try
   - line_length
   - type_body_length
   - function_body_length
   - file_length
   - implicit_getter
