# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Run UI tests"
  lane :ui_tests do
    run_tests(workspace: "gaios.xcworkspace",
              devices: ["iPhone 11"],
              scheme: "gaios")
  end
end
