# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Run build debug app"
  lane :build_debug do
    cocoapods()
    sh "cd .. && ./tools/fetch_gdk_binaries.sh"
    build_ios_app(
      configuration: "Debug",
      scheme: "gaios",
      workspace: "gaios.xcworkspace",
      #silent: true,
      clean: true,
      output_directory: "./debug",
      output_name: "Green-debug.ipa",
      skip_build_archive: true,
      skip_archive: true,
      include_bitcode: false,
      skip_codesigning: true
    )
  end

  desc "Run build dev app"
  lane :build_dev do
    cocoapods()
    sh "cd .. && ./tools/fetch_gdk_binaries.sh"
    build_ios_app(
      configuration: "Release",
      scheme: "gaios",
      workspace: "gaios.xcworkspace",
      #silent: true,
      clean: true,
      output_directory: "./dev",
      output_name: "Green-dev.ipa",
      include_bitcode: false,
      export_method: "ad-hoc",
      build_path: "./dev",
      archive_path: "./dev/Green.xcarchive",
      export_options: "./ExportOptions.plist",
      xcargs: "-allowProvisioningUpdates"
    )
  end

  desc "Run build release app"
  lane :build_release do
    cocoapods()
    sh "cd .. && ./tools/fetch_gdk_binaries.sh"
    build_ios_app(
      configuration: "Release",
      scheme: "gaios",
      workspace: "gaios.xcworkspace",
      #silent: true,
      clean: true,
      output_directory: "./release",
      output_name: "Green.ipa",
      include_bitcode: false,
      build_path: "./release",
      archive_path: "./release/Green.xcarchive",
      export_options: "./ExportOptions.plist",
      xcargs: "-allowProvisioningUpdates"
    )
    upload_to_testflight(
      apple_id: '1402243590',
      skip_waiting_for_build_processing: true
    )
  end

  desc "Run UI tests"
  lane :ui_tests do
    run_tests(workspace: "gaios.xcworkspace",
              devices: ["iPhone 11"],
              scheme: "gaios")
  end
end
