#!/bin/sh
# Use uncrustify to reformat the source
if test -z "$1"; then
    files=`ls ./app/src/main/java/com/greenaddress/*/*/*.java ./app/src/main/java/com/greenaddress/*/*/*/*.java | grep -v SwipeButton.java`
else
    files="$*"
fi
uncrustify --replace --no-backup -c tools/uncrustify.cfg $files
# Work around an uncrustify bug that splits member references
sed -i -e 's/ : : /::/g' -e 's/- >/->/g' $files
